// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADCy3yISudgPgjjmVwjyfArwvMAQb89m4',
    appId: '1:522341973463:web:0dd1e9fedde1b110b45f92',
    messagingSenderId: '522341973463',
    projectId: 'ih14a-gp41',
    authDomain: 'ih14a-gp41.firebaseapp.com',
    storageBucket: 'ih14a-gp41.firebasestorage.app',
    measurementId: 'G-J5V2TD6GQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSHZEYoL36mO3Y8zfYRi3Sd-1j75-jAL0',
    appId: '1:522341973463:android:9b7b4367bc2fc75ab45f92',
    messagingSenderId: '522341973463',
    projectId: 'ih14a-gp41',
    storageBucket: 'ih14a-gp41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZOYoHFh9VYGxezHZxxagbKjbR46mFLSk',
    appId: '1:522341973463:ios:d076ece496044ca2b45f92',
    messagingSenderId: '522341973463',
    projectId: 'ih14a-gp41',
    storageBucket: 'ih14a-gp41.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZOYoHFh9VYGxezHZxxagbKjbR46mFLSk',
    appId: '1:522341973463:ios:d076ece496044ca2b45f92',
    messagingSenderId: '522341973463',
    projectId: 'ih14a-gp41',
    storageBucket: 'ih14a-gp41.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADCy3yISudgPgjjmVwjyfArwvMAQb89m4',
    appId: '1:522341973463:web:70eab6474c19f837b45f92',
    messagingSenderId: '522341973463',
    projectId: 'ih14a-gp41',
    authDomain: 'ih14a-gp41.firebaseapp.com',
    storageBucket: 'ih14a-gp41.firebasestorage.app',
    measurementId: 'G-4MZKFMM59V',
  );

}